"""BG40 default data for Segmental Box Girder Pro.

Commercial M3B uses a report-driven data model while preserving the stable
calculation-engine inputs from M1. Internal UI units are kN, m, MPa, and mm.
"""

BG40_DEFAULT = {
    "meta": {
        "schema_version": "0.5.16-commercial-ui32b-prominent-trace-verification-actions",
        "source_file_schema_version": "0.5.16-commercial-ui32b-prominent-trace-verification-actions",
        "loaded_schema_version": "0.5.16-commercial-ui32b-prominent-trace-verification-actions",
        "schema_migration_status": "Current",
        "migration_target_schema_version": "0.5.16-commercial-ui32b-prominent-trace-verification-actions",
        "migration_complete": True,
        "migration_path": ["0.5.16-commercial-ui32b-prominent-trace-verification-actions"],
        "app_name": "Segmental Box Girder Pro",
        "dataset_status": "BG40 baseline loaded; AASHTO LRFD 2020 Section 5 governing concrete design basis and DPT seismic database active",
        "schema_note": "Report-driven workspace/subpage schema for commercial-grade QA, traceability, and future report export.",
        "baseline_report": "BG40_Final_Complete_R10.docx",
    },
    "project": {
        "name": "BG40",
        "description": "PT Segmental Box Girder · Track Doubling Project (Khon Kaen – Nong Khai)",
        "bridge_object": "B2_SPAN1",
        "span_m": 40.0,
        "width_m": 11.2,
        "depth_m": 2.5,
        "design_code": "AASHTO LRFD 2020 Section 5 + EN Actions",
        "tendon_system": "External / Unbonded PT",
        "units": "kN, m, MPa, mm",
        "workflow_note": "Three simply supported girder spans; one span is checked as BG40/B2_SPAN1.",
    },

    "code_basis": {
        "concrete_design_standard": "AASHTO LRFD Bridge Design Specifications, 9th Edition, 2020",
        "concrete_design_section": "Section 5 — Concrete Structures",
        "governing_status": "GOVERNING",
        "reference_file": "SECTION 5 CONCRETE STRUCTURES(1).pdf",
        "internal_units": "kN, m, MPa, mm",
        "unit_policy": "Store/display SI only; wrap AASHTO kip/ksi/in/ft equations with explicit internal conversion.",
        "legacy_note": "AASHTO LRFD 9th Edition (2020) is the active governing bridge design-code basis unless a project-specific legacy reference is explicitly documented."
    },
    "criteria": {
        "standards": [
            {"Code / Standard": "EUROCODE EN 1991", "Description": "Basis of design and actions on structures"},
            {"Code / Standard": "AASHTO LRFD Bridge Design Specifications, 9th Edition, 2020", "Description": "Primary concrete / prestressed-concrete bridge design standard — Section 5 governs this app"},
            {"Code / Standard": "ACI 318M-14", "Description": "Building code requirement for reinforced concrete"},
            {"Code / Standard": "CEB-FIP Model Code for Concrete, 1990", "Description": "Reference only; AASHTO governs creep, shrinkage, and prestress losses"},
            {"Code / Standard": "DPT 1302-61", "Description": "Thai seismic design standard"},
            {"Code / Standard": "DPT 1311-50", "Description": "Thai wind loading standard"},
            {"Code / Standard": "SRT requirements", "Description": "State Railway of Thailand requirements"},
            {"Code / Standard": "PCI Design Handbook (5th Ed.)", "Description": "Precast and prestressed concrete reference"},
        ],
        "units_statement": "SI units are used throughout this app and report workflow (kN, kN·m, MPa, m, mm). AASHTO LRFD Section 5 equations written in kip/ksi/in/ft are evaluated through explicit unit-safe conversion wrappers.",
        "combination_basis": "ULS and SLS load combinations are generated in the FEA model in accordance with EN 1990 and EN 1991-2 railway action principles. Design forces are taken from verified FEA envelopes.",
    },
    "materials": {
        "fc_mpa": 60.0,
        "fci_mpa": 60.0,
        "Ec_mpa": 36669.0,
        "fr_mpa": 4.88,
        "beta1": 0.65,
        "fy_mpa": 390.0,
        "fy_sd50_mpa": 490.0,
        "Ep_mpa": 197000.0,
        "fpu_mpa": 1861.6,
        "fpy_mpa": 1689.9,
        "fpi_mpa": 1395.0,
        "gamma_c_kn_m3": 24.5,
        "strand_diameter_mm": 15.20,
        "strand_area_mm2": 139.0,
        "strand_breaking_kn": 258.54,
        "relaxation_70_pct": 2.50,
        "relaxation_80_pct": 4.50,
    },
    "load_components": {
        "dead_load_definition": "Dead load is the vertical load due to the weight of the entire structure, including other components permanently attached thereto, such as walls, rails, concrete track supports, conduits for electrical cables, and other permanently installed tools, equipment, or appurtenances.",
        "dead_load_note": "Self-Weight (SW): for calculation purposes, the following unit weights shall be used. This page is informational/report text only; FEA self-weight remains generated in the structural analysis model.",
        "dead_load_unit_weights": [
            {"Material": "Steel", "Unit Weight (kN/m³)": 76.9, "Mass Density (kg/m³)": 7850, "Source": "BG40 Calculation Report Ch. 1.3.1"},
            {"Material": "Cast iron", "Unit Weight (kN/m³)": 70.6, "Mass Density (kg/m³)": 7200, "Source": "BG40 Calculation Report Ch. 1.3.1"},
            {"Material": "Plain concrete", "Unit Weight (kN/m³)": 23.5, "Mass Density (kg/m³)": 2400, "Source": "BG40 Calculation Report Ch. 1.3.1"},
            {"Material": "Reinforced concrete", "Unit Weight (kN/m³)": 24.5, "Mass Density (kg/m³)": 2500, "Source": "BG40 Calculation Report Ch. 1.3.1"},
            {"Material": "Prestressed concrete", "Unit Weight (kN/m³)": 24.5, "Mass Density (kg/m³)": 2500, "Source": "BG40 Calculation Report Ch. 1.3.1"},
            {"Material": "Ballast", "Unit Weight (kN/m³)": 18.6, "Mass Density (kg/m³)": 1900, "Source": "BG40 Calculation Report Ch. 1.3.1"},
        ],
        "sdl_components": [
            {"Component": "Rails w/Fastener", "Single Track (kN/m)": 1.46, "Double Track (kN/m)": 2.93, "Include": True, "Source": "BG40 R10", "Note": "Track component"},
            {"Component": "Track Supporting Structure (Plinth)", "Single Track (kN/m)": 20.00, "Double Track (kN/m)": 40.00, "Include": True, "Source": "BG40 R10", "Note": "Plinth / track support"},
            {"Component": "Signaling Equipment", "Single Track (kN/m)": 0.51, "Double Track (kN/m)": 0.51, "Include": True, "Source": "BG40 R10", "Note": "Equipment load"},
            {"Component": "Power Supply", "Single Track (kN/m)": 2.00, "Double Track (kN/m)": 2.00, "Include": True, "Source": "BG40 R10", "Note": "Utility load"},
            {"Component": "Telecommunication", "Single Track (kN/m)": 0.20, "Double Track (kN/m)": 0.20, "Include": True, "Source": "BG40 R10", "Note": "Utility load"},
            {"Component": "Parapet / Noise Barrier", "Single Track (kN/m)": 29.40, "Double Track (kN/m)": 29.40, "Include": True, "Source": "BG40 R10", "Note": "Permanent appurtenance"},
            {"Component": "Concrete Cable Box", "Single Track (kN/m)": 8.00, "Double Track (kN/m)": 8.00, "Include": True, "Source": "BG40 R10", "Note": "Permanent appurtenance"},
            {"Component": "Cables", "Single Track (kN/m)": 0.07, "Double Track (kN/m)": 0.15, "Include": True, "Source": "BG40 R10", "Note": "Cable load"},
            {"Component": "Drainage", "Single Track (kN/m)": 0.50, "Double Track (kN/m)": 1.00, "Include": True, "Source": "BG40 R10", "Note": "Drainage load"},
            {"Component": "Ballast (Ballastless - none)", "Single Track (kN/m)": 0.00, "Double Track (kN/m)": 0.00, "Include": True, "Source": "BG40 R10", "Note": "Ballastless track"},
        ],
        "design_sdl_single_kn_m": 65.0,
        "design_sdl_double_kn_m": 85.0,
        "live_load_model": "U20 (= 0.8 × LM71)",
        "u20_scale_factor": 0.80,
        "u20_udl_kn_m": 64.0,
        "u20_axle_label": "P from 0.8 × LM71 axle loads",
        "dynamic_L_left_m": 35.0,
        "dynamic_L_right_m": 40.0,
        "dynamic_factor_design": 1.20,
        "lf_traction_kn_m": 33.0,
        "lf_braking_kn_m": 20.0,
        "lf_length_m": 40.0,
        "lf_traction_cap_kn": 1000.0,
        "lf_braking_cap_kn": 6000.0,
        "hf_qsk_kn": 100.0,
        "hf_alpha": 0.80,
        "hf_reduce_alpha_below_one": False,
        "wind_province": "ขอนแก่น",
        "wind_province_area": "ทั้งจังหวัด",
        "wind_reference_group": "Group 1",
        "wind_v50_m_s": 25.0,
        "wind_terrain_factor": 1.0,
        "wind_vb0_m_s": 25.0,
        "wind_cdir": 1.0,
        "wind_cseason": 1.0,
        "wind_vb_m_s": 25.0,
        "wind_air_density_kg_m3": 1.25,
        "wind_b_m": 11.2,
        "wind_ze_m": 10.0,
        "wind_dtot_ws_m": 3.9,
        "wind_dtot_ws_wl_m": 6.8,
        "wind_c_ws": 4.6,
        "wind_c_ws_wl": 5.7,
        "wind_c_source": "Auto from EN 1991-1-4 Table 8.2 / BG40 R10 Table 2.5",
        "wind_use_manual_c": False,
        "seismic_region": "General Thailand",
        "seismic_province_th": "อุดรธานี",
        "seismic_district_th": "เมืองอุดรธานี",
        "seismic_soil_class": "D",
        "seismic_lookup_mode": "DPT database first; manual override only when location is not available or project-specific study governs",
        "seismic_Fa": 1.60,
        "seismic_Fv": 2.40,
        "seismic_damping_percent": 5.0,
        "seismic_bangkok_zone": 0,
        "seismic_Ss_g": 0.176,
        "seismic_S1_g": 0.045,
        "seismic_T_s": 0.835,
        "seismic_operational_category": "Essential",
        "seismic_substructure_key": "single_column_or_pier",
        "seismic_substructure_label": "Single column / single pier",
        "seismic_R_mode": "Auto from AASHTO LRFD 2020 Table 3.10.7.1-1",
        "seismic_importance_preset_key": "bg40_default",
        "seismic_I": 1.25,
        "seismic_R": 2.0,
        "seismic_R_source": "AASHTO LRFD 2020 Table 3.10.7.1-1 — Essential Bridge / Single column or pier",
        "seismic_I_source": "BG40 project default / project importance basis",
        "seismic_fea_adoption_mode": "Coefficient trace only — numeric EQ force generated in FEA model",
        "seismic_direction_basis": "EQX and EQY independent horizontal directions",
        "seismic_weight_source": "FEA mass / seismic weight W from analysis model",
        "seismic_adopted_coefficient_Cs": 0.0,
    },
    "bridge_model": {
        "bridge_type": "Precast Segmental PT Box Girder - Simple Span",
        "number_of_tracks": "Double Track",
        "analysis_program": "FEA program",
        "superstructure_element": "Shell Elements (4-node)",
        "tendon_element": "Internal Tendon Objects",
        "substructure_element": "Frame Elements",
        "foundation_model": "Frame Elements + Soil Springs",
        "support_conditions": [
            {"Support": "Left (x = 0 m)", "Vertical (DZ)": "Fixed", "Longitudinal (DX)": "Fixed (Pin)", "Transverse (DY)": "Fixed", "Rotation": "Free"},
            {"Support": "Right (x = 40 m)", "Vertical (DZ)": "Fixed", "Longitudinal (DX)": "Free (Roller)", "Transverse (DY)": "Fixed", "Rotation": "Free"},
        ],
    },
    "section": {
        "B_m": 11.200,
        "D_m": 2.500,
        "t_top_m": 0.260,
        "t_bot_m": 0.250,
        "t_web_m": 0.380,
        "web_inclination_deg": 15.32,
        "Ac_m2": 5.698,
        "I33_m4": 4.681,
        "I22_m4": 39.52,
        "J_m4": 8.846,
        "AS2_m2": 2.028,
        "S_top_m3": 5.577,
        "S_bottom_m3": 2.819,
        "xcg_from_left_m": 5.600,
        "xcg_from_right_m": 5.600,
        "Z33_m3": 4.057,
        "ycg_from_bottom_m": 1.661,
        "yt_from_top_m": 0.839,
        "ypna_m": 2.241,
        "R33_m": 0.906,
        "coordinate_source": "FEA keyed properties; import CSiBridge Structural/Opening Polygon coordinates to calculate geometry from x-y loops.",
        "coordinate_units": "mm",
        "coordinate_rows": [],
        "computed_from_coordinates": {},
        "J_method": "FEA / manual override",
        "J_thin_walled_m4": None,
        "J_thin_walled_difference_pct": None,
        "J_note": "Torsional constant J is retained from FEA/manual value unless a later advanced torsion solver is enabled.",
        "Aoh_mm2": 24260000.0,
        "ph_mm": 26102.0,
        "bv_mm": 380.0,
        "dv_mm": 1867.5,
        "dweb_mm": 2245.0,
        "tcr_knm": 31185.0,
    },
    "prestress": {
        "num_tendons": 16,
        "strands_per_tendon": 24,
        "Aps_per_tendon_mm2": 3360.0,
        "Aps_total_mm2": 53760.0,
        "mu_internal": 0.20,
        "mu_external": 0.15,
        "wobble_internal_per_m": 0.001,
        "wobble_external_per_m": 0.0,
        "anchor_set_mm": 6.0,
        "RH_percent": 75.0,
        "ti_days": 28.0,
        "tf_days": 27000.0,
        "crsh_construction_method": "Span-by-span segmental with precast segments",
        "segment_age_at_transport_days": 30.0,
        "span_assembly_duration_days": 0.0,
        "crsh_stage_time_basis": "Auto representative span mode",
        "crsh_calculation_route": "Refined / time-step — Recommended",
        "crsh_time_step_age_source": "Adopt computed prestressing age t_jack from 4.5 construction map",
        "crsh_creep_time_basis": "BG40 report-match incremental Δktd — Recommended audit route",
        "relaxation_calculation_method": "BG40 low-relaxation interaction cap — Recommended audit route",
        "relaxation_steel_type": "Low-relaxation strand",
        "relaxation_stress_basis": "Use fpj / jacking-stress preview",
        "u_outer_m": 25.98,
        "u_inner_m": 11.55,
        "u_total_m": 37.53,
        "crsh_drying_perimeter_basis": "Outer + inner void perimeter",
        "crsh_Ac_m2": 5.698,
        "V_over_S_m": 0.1518,
        "V_over_S_mm": 151.8,
        "V_over_S_in": 5.98,
        "h0_m": 0.3036,
        "fcgp_mpa": 36.26,
        "fcgp_stage_source_mode": "Auto-calculated / read-only",
        "fcgp_auto_stage_mpa": 36.26,
        "fcgp_manual_override_enabled": False,
        "fcgp_manual_override_mpa": 36.26,
        "fcgp_stage_source_note": "Adopted BG40 stage-stress source; future staged-analysis importer may replace this value without exposing f_cgp as a main-page input.",
        "anchor_set_loss_mpa": 0.0,
        "relaxation_loss_mpa": 0.0,
        "tendon_friction_groups": [
            {"group": "T1–T2", "n": 4, "end_dp_m": 1.89, "midspan_dp_m": 2.15, "alpha_vert_rad": 0.0260, "alpha_horiz_rad": 0.0720},
            {"group": "T3–T4", "n": 4, "end_dp_m": 1.46, "midspan_dp_m": 2.15, "alpha_vert_rad": 0.0689, "alpha_horiz_rad": 0.0620},
            {"group": "T5–T6", "n": 4, "end_dp_m": 1.03, "midspan_dp_m": 2.15, "alpha_vert_rad": 0.1120, "alpha_horiz_rad": 0.0120},
            {"group": "T7–T8", "n": 4, "end_dp_m": 0.60, "midspan_dp_m": 1.85, "alpha_vert_rad": 0.1248, "alpha_horiz_rad": 0.0471},
        ],
        "dp_avg_end_m": 1.245,
        "dp_avg_midspan_m": 2.075,
        "eccentricity_midspan_m": 1.236,
        "jacking_operation_basis": "One-end stressing / JackFrom = Start",
        "stressing_basis_gate_status": "PENDING ADOPTED TENDON JACKFROM",
        "stressing_mode_basis": "Read from adopted CSiBridge General tendon table JackFrom field before friction / anchor-set loss calculation.",
        "jacking_force_interpretation": "Jacking force is tendon axial force per tendon. Do not double the total prestressing force when a tendon is stressed from two ends; stressing end controls friction/anchor-set distribution, not Aps or total axial force.",
        "loss_source_gate_status": "SOURCE GATE REQUIRED",
        "loss_calculation_readiness_status": "BLOCKED UNTIL ADOPTED TENDON SOURCE IS LOCKED",
        "loss_readiness_basis": "PSLOSS.5 readiness register checks adopted tendon summary, JackFrom/stressing basis, section properties, CR&SH parameters, span/stage basis, and the friction formula trace before detailed effective-prestress adoption.",
        "friction_source_model_status": "SOURCE BLOCKED UNTIL ADOPTED TENDON PROFILE AND JACKFROM ARE LOCKED",
        "friction_preview_basis": "4.2 Friction uses adopted tendon station profile, external tendon friction coefficient μ, wobble coefficient K, and JackFrom route trace; preview results are not final adopted effective prestress.",
        "friction_formula_trace_status": "REPORT EQUATION TRACE ONLY; NOT ADOPTED INTO EFFECTIVE PRESTRESS",
        "friction_formula_trace_basis": "ΔfpF = fpj[1 − exp{−(Kx + μα)}], fpx = fpj − ΔfpF, and Loss % = ΔfpF/fpj × 100 are displayed as full equation blocks with tendon-by-tendon Kx, μα, exponent, exponential factor, ΔfpF, and fpx audit columns.",
        "friction_loss_summary_card_status": "LOSS-TYPE RESULT SUMMARY CARD PATTERN ACTIVE",
        "friction_loss_summary_card_basis": "4.2 Friction shows special top result cards for source status, governing tendon / maximum friction loss, minimum fpx after friction, and preview-only adoption status; future loss pages should follow the same pattern.",
        "friction_governing_tie_status": "GOVERNING TENDON TIES REPORTED",
        "friction_governing_tie_basis": "When mirrored tendons have equal maximum friction loss, the result cards and report summary list all governing tendons within the displayed MPa tolerance instead of only the first representative row.",
        "friction_full_tendon_report_status": "FULL TENDON REPORT DISPLAY",
        "friction_full_tendon_report_basis": "Tendon-by-tendon friction preview and calculation trace include a row-count note and display all adopted tendon rows in report review.",
    },
    "tendon_layout": {
        "active_bridge_object": "B2_SPAN1",
        "map_bridge_objects_to_active": True,
        "positive_horiz_offset_direction": "left",
        "section_overlay_dimension_mode": "clean",
        "general_rows": [],
        "vertical_rows": [],
        "horizontal_rows": [],
        "model": {},
        "source_meta": {},
        "adopted_model": {},
        "adopted_model_fingerprint": "",
        "adopted_downstream_summary": {},
        "adopted_source_trace": [],
        "adopted_at_utc": "",
        "adopted_status": "NOT ADOPTED: BG40 R10 baseline pending explicit CSiBridge tendon adoption",
        "source_note": "Import CSiBridge tendon General / Vertical / Horizontal tables to generate layout figures, then explicitly adopt the tendon model before downstream use.",
    },
    "fea_results": {
        "source_status": "FEA.5E three-stage CSiBridge source QA, governing trace, and downstream-readiness closeout; downstream design remains disconnected.",
        "axis_convention": {
            "status": "CONFIRMED FOR ACTIVE APP AXES",
            "source_program": "CSiBridge",
            "mapping": {"P": "Axial", "V2": "Vy", "T": "Torsion", "M3": "Mx"},
            "policy": "Retain source field names for traceability; require explicit mapping confirmation for non-CSiBridge imports.",
        },
        "import_schema_version": "1.0",
        "stage_imports": {
            "uls": {},
            "transfer": {},
            "service": {},
        },
        "import_attempts": {
            "uls": {},
            "transfer": {},
            "service": {},
        },
        "downstream_connection": {
            "status": "NOT YET CONNECTED",
            "connected_modules": [],
            "source_package_fingerprint": "",
            "note": "Sections 6–9 continue to use existing BG40/keyed demands until a separately reviewed connection milestone is implemented.",
        },
        "envelope_interpretation": "SINGLE STATE rows preserve simultaneous P-V2-T-M3 vectors. COMPONENT ENVELOPE Max/Min rows may be non-simultaneous. Compact rows store separate scalar extrema and are not one force vector.",
        "permanent_moment_midspan_knm": 47671.0,
        "prestress_moment_midspan_knm": -79731.0,
        "prestress_axial_midspan_kn": -64305.0,
        "ll_im_moment_min_knm": 0.0,
        "ll_im_moment_max_knm": 37194.0,
    },
    "loads": {
        "critical_x_m": 38.133,
        "Vu_kn": 12153.0,
        "Tu_knm": 9211.9,
        "Pu_kn": -1108.0,
        "Mu_knm": 19266.0,
        "Vc_per_web_kn": 2145.0,
        "theta_deg_for_shear": 21.8,
        "beta_for_shear": 4.70,
        "fea_Al_max_mm2": 17381.0,
        "stirrup_bar_dia_mm": 25.0,
        "stirrup_spacing_mm": 250.0,
        "stirrup_legs_per_web": 2,
    },
    "rail_loads": {
        "speed_kmh": 160.0,
        "radius_m": 10000.0,
        "Lf_m": 40.0,
        "cf_track_condition": "Curved track / finite radius",
        "cf_assessment_threshold_percent": 2.0,
        "cf_include_in_fea": False,
        "cf_application_level": "Rail level",
        "cf_direction": "Radial / transverse to track",
        "cf_adoption_mode": "Factor only — not adopted as FEA load",
    },
    "uls_flexure": {
        "fps_mpa": 1499.0,
        "phi_mn_midspan_knm": 161530.0,
        "mu_midspan_knm": 121146.0,
        "max_dcr": 0.849,
        "governing_x_m": 15.0,
        "status": "PASS",
    },
    "sls_stress": {
        "transfer_top_mpa": -7.688,
        "transfer_bottom_mpa": -29.882,
        "final_top_mpa": -13.961,
        "final_bottom_mpa": -18.149,
        "governing_margin_percent": 17.0,
        "status": "PASS",
    },
    "deflection": {
        "limit_live_load_mm": 50.0,
        "transfer_camber_mm": 45.936,
        "final_net_camber_mm": 22.364,
        "final_ll_deflection_mm": 20.098,
        "ll_utilization_percent": 40.2,
        "status": "PASS",
    },
}
